language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t basicpail/react-test-app -f ./frontend/Dockerfile.dev ./frontend #./frontend/Dockerfile.dev 의 빌드 스크립트에서 참조되는 파일들의 경로가 ./frontend 디렉터리에 있는 파일들이다?

script:
  - docker run -e CI=true basicpail/react-test-app npm run test

after_success:
  - docker build -t basicpail/docker-frontend-app ./frontend #Dockerfile은 자동으로 찾아지기에 도커파일의 경로를 생략해도 된다.
  - docker build -t basicpail/docker-backend-app ./backend
  - docker build -t basicpail/docker-server-app ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push basicpail/docker-frontend-app
  - docker push basicpail/docker-backend-app
  - docker push basicpail/docker-server-app