version: "2.4"

services:
  frontend:
    image: "basicpail93/docker-frontend-app"
    container_name: "frontend"
    volumes:
      - /home/ssg/app/node_modules
      - ./frontend:/home/ssg/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: "basicpail93/docker-server-app"
    container_name: "server"
    ports:
      - "80:80"
    # mem_limit: 128m
    # links:
    #   - frontend
    #   - backend
  
  backend:
    image: "basicpail93/docker-backend-app"
    container_name: "backend"
    volumes:
      - /home/ssg/app/node_modules
      - ./backend:/home/ssg/app
    environment: 
      MYSQL_HOST: $MYSQL_HOST 
      MYSQL_USER: $MYSQL_USER 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT  
    mem_limit: 128m

# version: "3"
# services:
#   frontend:
#     build:
#       dockerfile: Dockerfile.dev
#       context: ./frontend #./frontend 디렉터리안에 build된 파일들이 들어간다고? build하면 기본적으로 build라는 디렉터리가 생기는거 아니가?
#     container_name: app_frontend
#     volumes:
#       - /home/ssg/app/node_modules
#       - ./frontend:/home/ssg/app
#     stdin_open: true

#   nginx:
#     restart: always
#     build:
#       dockerfile: Dockerfile
#       context: ./nginx
#     container_name: app_server
#     ports:
#       - "3000:80"

#   backend:
#     build:
#       dockerfile: Dockerfile.dev
#       context: ./backend
#     container_name: app_backend
#     volumes:
#       - /home/ssg/app/node_modules
#       - ./backend:/home/ssg/app
#     environment:
#       MYSQL_HOST: mysql
#       MYSQL_USER: root
#       MYSQL_ROOT_PASSWORD: basicpail
#       MYSQL_DATABASE: myapp
#       MYSQL_PORT: 3306

#   # mysql:
#   #   build: ./mysql
#   #   restart: unless-stopped
#   #   container_name: app_db
#   #   ports:
#   #     - "3306:3306"
#   #   volumes:
#   #     - ./mysql/mysql_data:/var/lib/mysql
#   #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
#   #   environment:
#   #     MYSQL_ROOT_PASSWORD: root
#   #     MYSQL_DATABASE: myapp