name: Deploy FullStackApp
on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t basicpail93/react-test-app -f ./frontend/Dockerfile.dev ./frontend
      - run: docker run -e CI=true basicpail93/react-test-app npm test

      - run: docker build -t basicpail93/docker-frontend-app ./frontend
      - run: docker build -t basicpail93/docker-server-app ./nginx
      - run: docker build -t basicpail93/docker-backend-app ./backend

      - run: docker push basicpail93/docker-frontend-app
      - run: docker push basicpail93/docker-server-app
      - run: docker push basicpail93/docker-backend-app

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-fullstack-ga-app
          environment_name: Docker-fullstack-ga-app-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-242201304740
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip

